@extends('layouts.app')
@php($status = $server->latestStatus)
@php($statusState = \App\Models\ServerStatus::stateOf($status))
@php($isOnline = $statusState === 'online')
@section('title', $server->name.' — Speed.mn серверийн төлөв')
@section('description', $server->name.' серверийн бодит цагийн төлөв, тоглогчдын тоо, газрын зураг болон холболтын мэдээлэл.')
@section('content')
<section class="page-head"><div class="shell"><a class="back" href="{{ route('servers.index') }}">← Бүх сервер</a><div class="detail-title"><div><span class="game-pill {{ $server->game }}">{{ $server->game === 'cs2' ? 'CS2' : 'CS 1.6' }}</span><h1>{{ $server->name }}</h1><p class="muted">{{ $server->address }} · {{ $server->region ?: 'Монгол' }}</p></div><div class="card-actions"><button class="button button-ghost copy-address" type="button" data-copy-address="{{ $server->address }}">IP хуулах</button><a class="button button-primary" href="steam://connect/{{ $server->address }}">Серверт холбогдох</a></div></div>
@auth
<form class="favorite-form detail-favorite" method="POST" action="{{ route(($server->is_favorited ?? false) ? 'servers.unfavorite' : 'servers.favorite', $server) }}">@csrf @if($server->is_favorited ?? false) @method('DELETE') @endif<button class="favorite-button" type="submit" aria-pressed="{{ ($server->is_favorited ?? false) ? 'true' : 'false' }}">{{ ($server->is_favorited ?? false) ? '★ Дуртайгаас хасах' : '☆ Дуртайд хадгалах' }}</button></form>
@endauth
</div></section>
<section class="shell section"><div class="detail-grid">
<div class="panel"><div class="panel-heading"><h2>Серверийн төлөв</h2><span class="status {{ $statusState }}"><i></i>{{ ['online' => 'ОНЛАЙН', 'offline' => 'ОФЛАЙН', 'stale' => 'МЭДЭЭЛЭЛ ХУУЧИРСАН', 'unknown' => 'МЭДЭЭЛЭЛ АЛГА'][$statusState] }}</span></div>@if($status?->created_at)<p class="updated-at">Сүүлд шалгасан <time datetime="{{ $status->created_at->toIso8601String() }}">{{ $status->created_at->timezone('Asia/Ulaanbaatar')->format('Y-m-d H:i') }}</time> (УБ)</p>@else<p class="updated-at">Статусын мэдээлэл хараахан ирээгүй</p>@endif<div class="detail-metrics"><div><small>ТОГЛОГЧ</small><strong>{{ $isOnline ? $status->players : '—' }}/{{ $status?->max_players ?: $server->max_players ?: '—' }}</strong></div><div><small>ГАЗРЫН ЗУРАГ</small><strong>{{ $status?->map ?: '—' }}</strong></div><div><small>ХОЦРОЛТ</small><strong>{{ $status?->response_time !== null ? $status->response_time.' мс' : '—' }}</strong></div><div><small>ХУВИЛБАР</small><strong>{{ $status?->version ?: '—' }}</strong></div><div><small>VAC ХАМГААЛАЛТ</small><strong>{{ $status?->vac === null ? '—' : ($status->vac ? 'ИДЭВХТЭЙ' : 'УНТРААЛТТАЙ') }}</strong></div><div><small>БОТ</small><strong>{{ $status?->bots ?? '—' }}</strong></div></div></div>
<div class="panel"><div class="panel-heading"><h2>Серверийн түүх</h2><small class="muted">{{ number_format($totalChecks) }} шалгалт</small></div><nav class="history-period" aria-label="Түүхийн хугацаа">@foreach(['24h' => '24 цаг', '7d' => '7 хоног', '30d' => '30 хоног'] as $value => $label)<a class="{{ $period === $value ? 'active' : '' }}" href="{{ route('servers.show', ['server' => $server, 'period' => $value]) }}" @if($period === $value) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav><div class="history-summary"><div><small>UPTIME</small><strong>{{ $uptime === null ? '—' : number_format($uptime, 2).'%' }}</strong></div><div><small>ДУНДАЖ ТОГЛОГЧ</small><strong>{{ $averagePlayers === null ? '—' : number_format($averagePlayers, 1) }}</strong></div><div><small>ОРГИЛ ТОГЛОГЧ</small><strong>{{ $peakPlayers ?? '—' }}</strong></div></div>
@if($period === '24h')<small class="muted">Тоглогчдын тоо</small><div class="history">@forelse($history as $point)<div style="height:{{ $point->players === null ? 8 : min(100, max(8, ($point->players / max(1, $server->max_players ?: $point->max_players ?: 1)) * 100)) }}%" class="{{ $point->online ? 'bar-online' : 'bar-offline' }}" title="{{ $point->created_at?->format('Y-m-d H:i').' · '.($point->players ?? '—').' тоглогч' }}"></div>@empty<p class="muted">Хяналтын мэдээлэл алга.</p>@endforelse</div><small class="muted">Хариу өгөх хугацаа</small><div class="history">@foreach($history as $point)<div style="height:{{ $point->response_time === null ? 8 : min(100, max(8, $point->response_time / max(1, $history->max('response_time') ?: 1) * 100)) }}%; background:#8b5cf6" title="{{ $point->response_time === null ? 'Хариу алга' : $point->response_time.' мс' }}"></div>@endforeach</div>
@else<small class="muted">Өдөр тутмын uptime</small><div class="history history-daily">@forelse($history as $point)@php($dailyUptime = $point->checks ? (int) round($point->online_checks / $point->checks * 100) : 0)<div class="bar-online" style="height:{{ max(8, $dailyUptime) }}%" title="{{ $point->bucket }} · {{ number_format($dailyUptime, 1) }}% uptime · оргил {{ $point->peak_players ?? '—' }} тоглогч"></div>@empty<p class="muted">Хяналтын мэдээлэл алга.</p>@endforelse</div>@endif
</div>
<div class="panel"><div class="panel-heading"><h2>Холболтгүй байсан түүх</h2><small class="muted">Сүүлийн {{ $periodDays === 1 ? '24 цаг' : $periodDays.' хоног' }}</small></div>@forelse($offlineHistory as $point)<p class="muted">{{ $point->created_at?->timezone('Asia/Ulaanbaatar')->format('Y-m-d H:i') }} — хариу өгөөгүй</p>@empty<p class="muted">Холболтгүй төлөв бүртгэгдээгүй.</p>@endforelse</div>
<div class="panel player-panel"><div class="panel-heading"><h2>Тоглогчид</h2><small class="muted">{{ $isOnline ? ($status?->players ?? 0) : 0 }} тоглож байна</small></div>@if($isOnline && $status?->player_list)<div class="player-list">@foreach($status->player_list as $player)<div class="player-row"><strong>{{ $player['name'] ?? 'Тоглогч' }}</strong><span>{{ $player['score'] ?? '—' }} оноо</span><span>{{ isset($player['duration']) ? gmdate('H:i:s', max(0, (int) $player['duration'])) : '—' }}</span></div>@endforeach</div>@else<p class="muted">Тоглогчдын мэдээлэл одоогоор алга.</p>@endif</div>
</div></section>
@endsection
