@extends('layouts.app')
@php($status = $server->latestStatus)
@section('title', $server->name.' — Speed.mn')
@section('content')
<section class="page-head"><div class="shell"><a class="back" href="{{ route('servers.index') }}">← All servers</a><div class="detail-title"><div><span class="game-pill {{ $server->game }}">{{ $server->game === 'cs2' ? 'CS2' : 'CS 1.6' }}</span><h1>{{ $server->name }}</h1><p class="muted">{{ $server->address }} · {{ $server->region ?: 'Mongolia' }}</p></div><a class="button button-primary" href="steam://connect/{{ $server->address }}">Connect to server</a></div></div></section>
<section class="shell section"><div class="detail-grid">
<div class="panel"><div class="panel-heading"><h2>Server status</h2><span class="status {{ $status?->online ? 'online' : 'offline' }}"><i></i>{{ $status?->online ? 'ONLINE' : 'OFFLINE' }}</span></div><div class="detail-metrics"><div><small>PLAYERS</small><strong>{{ $status?->players ?? '—' }}/{{ $status?->max_players ?: $server->max_players ?: '—' }}</strong></div><div><small>MAP</small><strong>{{ $status?->map ?: '—' }}</strong></div><div><small>RESPONSE</small><strong>{{ $status?->response_time !== null ? $status->response_time.' ms' : '—' }}</strong></div><div><small>VERSION</small><strong>{{ $status?->version ?: '—' }}</strong></div><div><small>VAC</small><strong>{{ $status?->vac === null ? '—' : ($status->vac ? 'SECURED' : 'OFF') }}</strong></div><div><small>BOTS</small><strong>{{ $status?->bots ?? '—' }}</strong></div></div></div>
<div class="panel"><div class="panel-heading"><h2>24-hour monitoring</h2><small class="muted">{{ $history->count() }} checks</small></div><p><strong>{{ $uptime === null ? '—' : $uptime.'%' }}</strong> uptime</p><small class="muted">Players</small><div class="history">@forelse($history as $point)<div style="height:{{ $point->players === null ? 8 : min(100, max(8, ($point->players / max(1, $server->max_players ?: $point->max_players ?: 1)) * 100)) }}%" class="{{ $point->online ? 'bar-online' : 'bar-offline' }}" title="{{ $point->created_at?->format('M j, H:i').' · '.($point->players ?? '—').' players' }}"></div>@empty<p class="muted">No monitoring data yet.</p>@endforelse</div><small class="muted">Response time</small><div class="history">@foreach($history as $point)<div style="height:{{ $point->response_time === null ? 8 : min(100, max(8, $point->response_time / max(1, $history->max('response_time') ?: 1) * 100)) }}%; background:#8b5cf6" title="{{ $point->response_time === null ? 'No response' : $point->response_time.' ms' }}"></div>@endforeach</div></div>
<div class="panel"><div class="panel-heading"><h2>Offline history</h2><small class="muted">Last 24 hours</small></div>@forelse($offlineHistory as $point)<p class="muted">{{ $point->created_at?->format('M j, H:i') }} — no response</p>@empty<p class="muted">No offline checks recorded.</p>@endforelse</div>
<div class="panel player-panel"><div class="panel-heading"><h2>Players</h2><small class="muted">{{ $status?->players ?? 0 }} online</small></div>@if($status?->player_list)<div class="player-list">@foreach($status->player_list as $player)<div class="player-row"><strong>{{ $player['name'] ?? 'Unknown player' }}</strong><span>{{ $player['score'] ?? '—' }} score</span><span>{{ isset($player['duration']) ? gmdate('H:i:s', max(0, (int) $player['duration'])) : '—' }}</span></div>@endforeach</div>@else<p class="muted">Player details are not available from this server.</p>@endif</div>
</div></section>
@endsection
