[program:speedmn-demo-parser]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/awe/current/artisan queue:work database --queue=demo-parsing --sleep=3 --tries=1 --timeout=1860 --max-time=3600
directory=/var/www/awe/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/awe/storage/logs/demo-parser.log
stopwaitsecs=1900