[program:speedmn-scheduler]
process_name=%(program_name)s
command=/usr/bin/php /var/www/awe/current/artisan schedule:work
directory=/var/www/awe/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/awe/storage/logs/scheduler.log
stopwaitsecs=60
