[program:speedmn-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/speed.mn/artisan queue:work database --sleep=3 --tries=3 --timeout=30 --max-time=3600
directory=/var/www/speed.mn
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/speed.mn/storage/logs/worker.log
stopwaitsecs=60
